### ISSUE TITLE
Storage fraction with nans in flow series

### ISSUE THREAD

**Issue by mcmillanhk** [TOSSHtoolbox/TOSSH#1]
I've been getting very large values of total storage in cases where the streamflow series has nans. It seems to be because field capacity is also very large in these cases, which in turn is due to a steep rise in the modelled storage during the nan period. I tried replacing nans with the mean flow rather than the median flow (seems to make more sense if the average outflow should match with the non-nan period), but storage is still jumpy in the nan period. Wondering if for nan period (at least maybe nan period longer than a certain length) the period should be removed altogether from the series?

**Comment by mcmillanhk** [comment]
[LUQ_IC_day.zip](https://github.com/TOSSHtoolbox/TOSSH/files/7112510/LUQ_IC_day.zip)

Here's the file and code I was using

TOSSH_signatures_LUQ_IC_daily = calc_McMillan_Groundwater(num2cell(data.Q,1), ...
    num2cell(data.t,1), num2cell(data.P,1), num2cell(data.PET,1), ...
    'start_water_year',10,'recession_length',2,'n_start',1,...
    'eps',median(data.Q,'omitnan')*0.001,'plot_results',true);

**Comment by SebastianGnann** [comment]
Hm, I guess then perhaps the full year could be removed, so that there's no jump from say December to July if that's the NaN period. Generally, I am not very convinced of the usefulness of the storage fraction as it is currently implemented, as it gives very unrealistic values for most places (without any NaNs) and as the plots suggest that this signature doesn't work well for catchments that are different to the original ones it was designed for (in Luxembourg).

**Comment by SebastianGnann** [comment]
I have now changed the way NaN values are handled. They are assigned the mean value which leads to more stable storage values. This might, however, not be the best solution for time series with a lot of NaN values. For such series I would recommend removing the NaN periods manually before calculating the signature.
